#!/usr/bin/env bash

# DOTFILES_ROOT=$(dirname "${BASH_SOURCE[0]:-$0}")
DOTFILES_ROOT=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd -P)

set -e

RED=$'\e[1;31m'
GREEN=$'\e[1;32m'
END=$'\e[0m'

fail () {
  printf "${RED}[ FAIL ] $1\n"
  echo ""
  exit 1
}

success () {
  printf "${GREEN}[ OK ] $1\n"
}

# ----------------------
# Install tools
# ----------------------

install_homebrew() {
  echo "Setup Homebrew..."
  # install homebrew
  if hash brew 2>/dev/null; then
    echo "Already installed Homebrew"
  else
    echo "Installing Homebrew..."

    if test "$(uname -m)" = "x86_64"; then
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    elif test "$(uname)" = "arm64"; then
      echo "Installing to /usr/local for using emulation with Rosseta 2 (1/2)"
      arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      echo "Installing to /opt/homebrew for natively running on macOS ARM (2/2)"
      cd /opt
      mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
    fi

    success 'Homebrew'
  fi
}

install_packages_via_homebrew() {
  echo "Installing packages via Homebrew..."

  if ! command -v brew >/dev/null 2>&1; then
    echo "brew command could not be found"
    exit
  fi

  if [ ! -f "$DOTFILES_ROOT/brew/Brewfile" ]; then
    fail '.Brewfile was not found.'
  fi

  ln -s "$DOTFILES_ROOT/brew/Brewfile" "$HOME/.Brewfile"
  [ ! -L "$HOME/.Brewfile" ] && echo '.BrewFile not found.'

  ls -l "$HOME/.Brewfile"

  export HOMEBREW_BUNDLE_MAS_SKIP=$(brew bundle list --global --mas | paste -sd " " -)
  brew bundle install --global
  wait

  success 'Packages Installation by Homebrew'
}

setup_anyenv() {
  echo "Setup anyenv..."

  if command anyenv -v &> /dev/null; then
    echo "anyenv is already installed."
  else
    echo "Install anyenv..."
    brew install anyenv

    echo "Initialize anyenv"
    anyenv init

    mkdir -p $(anyenv root)/plugins
    git clone "https://github.com/znz/anyenv-update.git" "$(anyenv root)/plugins/anyenv-update"
  fi

  anyenv init
  # exec $SHELL -l

  # mkdir -p $(anyenv root)/plugins
  # git clone "https://github.com/znz/anyenv-update.git" "$(anyenv root)/plugins/anyenv-update"

  # anyenv update || true
  # anyenv install nodenv
  # anyenv install rbenv

  success 'Setup anyenv'
}

set_default_shell() {
  if [[ "$SHELL" != "/usr/local/bin/zsh" ]]; then
    sudo bash -c 'echo "/usr/local/bin/zsh" >> /etc/shells'
    sudo chsh -s /usr/local/bin/zsh

    success 'Setup default shell'
  fi
}

# ----------------------
# Set symlinks
# ----------------------

create_symlinks() {
  echo "Create symlinks..."

  for file in .??*
  do
    [ "$file" = ".git" ] && continue
    [ "$file" = ".github" ] && continue
    [ "$file" = ".vimrc.*" ] && continue

    local src="$DOTFILES_ROOT/$file"
    local dst="$HOME/$file"

    if [[ -f "$dst" || -d "$dst" || -L "$dst" ]]; then
      printf "File already exists."
      continue
    fi

    ln -s $src $dst
    success "linked $src to $dst"
  done

  success 'Symlinks'
}

# ----------------------
# zsh
# ----------------------

install_zsh_tools() {
  /bin/zsh $DOTFILES_ROOT/scripts/install-prezto.zsh

  success 'Setup zsh tools'
}

if [ $1 -eq "all" ] || [ -z $1 ]; then
  install_homebrew
  install_packages_via_homebrew
  install_zsh_tools

  set_default_shell
  setup_anyenv

  create_symlinks
fi
