# ------------------
# #Plugin sets
# -------------------

# Edit{{{

# Align 整形
[[plugins]]
repository = 'Align'
# surround.vim
[[plugins]]
repository = 'tpope/vim-surround'
# true/false切り替え
[[plugins]]
repository = 'taku-o/vim-toggle'
# コメントアウト
[[plugins]]
repository = 'tomtom/tcomment_vim'
# テキスト整形
[[plugins]]
repository = 'godlygeek/tabular'
# }}}


# Searching/Moving{{{
# smooth_scroll.vim スクロール
[[plugins]]
repository = 'yuroyoro/smooth_scroll.vim'
# 単語移動
# 「%」対応括弧へのカーソル移動を拡張
[[plugins]]
repository = 'matchit.zip'
# }}}


# color scheme
[[plugins]]
repository = 'tomasr/molokai'

# ステータスラインの色変更(powerlineから乗り換え)
[[plugins]]
repository = 'bling/vim-airline'

# Unit.vim
[[plugins]]
repository = 'Shougo/unite.vim'
[[plugins]]
repository = 'Shougo/neomru.vim'
[[plugins]]
repository = 'monochromegane/unite-yaml'
# vimfiler.vim
[[plugins]]
repository = 'Shougo/vimfiler'
# 行末の半角スペースを可視化
[[plugins]]
repository = 'bronson/vim-trailing-whitespace'


# Utility {{{

#PATHの設定を自動化
[[plugins]]
repository = 'tpope/vim-bundler'
# git plugin
[[plugins]]
repository = 'tpope/vim-fugitive'
# Helpを日本語化
[[plugins]]
repository = 'vim-jp/vimdoc-ja'
# 検索・置換機能強化
[[plugins]]
repository = 'tpope/vim-abolish'
# インデント表示
[[plugins]]
repository = 'nathanaelkane/vim-indent-guides'
# マークを可視化
[[plugins]]
repository = 'jacquesbh/vim-showmarks'
# }}}
