# ------------------
# #Plugin Lazy sets
# -------------------

# Edit{{{

# Completion {{{
# neocomplete.vim
[[plugins]]
repository = 'Shougo/neocomplete.vim'
insert = 1

[[plugins]]
repository = 'Shougo/neosnippet.vim'
depends = ['Shougo/neosnippet-snippets', 'honza/vim-snippets']
insert = 1
filetypes = 'neosnippet'

# }}}


# Languages {{{

# html

[[plugins]]
repository = 'othree/html5.vim'
filetypes = ['html']

[[plugins]]
repository = 'hokaccha/vim-html5validator'
filetypes = ['html']

# ブラウザの自動リロード(Mac only!)
[[plugins]]
repository = 'tell-k/vim-browsereload-mac'
filetypes = ['html']

# CSS
[[plugins]]
repository = 'hail2u/vim-css3-syntax'
filetypes = ['css']

[[plugins]]
repository = 'csscomb/vim-csscomb'
filetypes = ['css', 'scss']

# sass
[[plugins]]
repository = 'cakebaker/scss-syntax.vim'
filetypes = ['scss']

[[plugins]]
repository = 'AtsushiM/sass-compile.vim'
filetypes = ['scss']
depends = 'AtsushiM/search-parent.vim'

[[plugins]]
repository = 'mattn/emmet-vim'
filetypes = ['html', 'jade', 'css', 'scss']

# XML,HTMLの編集強化
[[plugins]]
repository = 'xmledit'
filetypes = ['html', 'xml']

# haml
[[plugins]]
repository = 'haml.zip'
filetypes = 'haml'

# jade
[[plugins]]
repository = 'digitaltoad/vim-jade'
filetypes = 'jade'

# JavaScript
[[plugins]]
repository = 'JavaScript-syntax'
filetypes = 'JavaScript'

[[plugins]]
repository = 'moll/vim-node'
filetypes = 'JavaScript'

[[plugins]]
repository = 'elzr/vim-json'
filetypes = 'json'

[[plugins]]
repository = 'mattn/jscomplete-vim'
filetypes = 'JavaScript'

# jQuery
[[plugins]]
repository = 'jQuery'
filetypes = 'JavaScript'

# coffee script
[[plugins]]
repository = 'kchmck/vim-coffee-script'
filetypes = 'coffee'

# C
[[plugins]]
repository = 'Rip-Rip/clang_complete'
filetypes = ['c', 'cpp']

# toml(設定ファイル書いたり)
[[plugins]]
repository = 'cespare/vim-toml'
filetypes = 'toml'

[[plugins]]
repository = 'stephpy/vim-yaml'
filetypes = 'yaml'

# }}}

# Markdown {{{
[[plugins]]
repository = 'plasticboy/vim-markdown'
filetypes = ['markdown', 'md']

[[plugins]]
repository = 'kannokanno/previm'
filetypes = ['markdown', 'md', 'rst']
depends = 'tyru/open-browser.vim'

#URLからブラウザを開く
[[plugins]]
repository = 'tyru/open-browser.vim'
filetypes = ['markdown', 'md', 'rst']
mappings = '<Plug>'


# }}}

# Development {{{
[[plugins]]
repository = 'thinca/vim-quickrun'
mappings = '<Plug>'
# }}}

# Searching/Moving{{{
# The Silver seacher
[[plugins]]
repository = 'rking/ag.vim'
mappings = '<Plug>'

# Lint or Checker Tools

[[plugins]]
repository = 'osyo-manga/shabadou.vim'

[[plugins]]
repository = 'cohama/vim-hier'

[[plugins]]
repository = 'dannyob/quickfixstatus'

[[plugins]]
repository = 'KazuakiM/vim-qfstatusline'

[[plugins]]
repository = 'KazuakiM/vim-qfsigns'

# [[plugins]]
# repository = 'osyo-manga/vim-watchdogs'
# depends = ['thinca/vim-quickrun', 'osyo-manga/shabadou.vim', 'cohama/vim-hier', 'dannyob/quickfixstatus', 'Shougo/vimproc']

[[plugins]]
repository = 'scrooloose/syntastic'
filetypes = ['all']

# }}}

# Utility {{{

# 編集履歴をツリー表示
[[plugins]]
repository = 'sjl/gundo.vim'
mappings = '<Plug>'

# vimshell
[[plugins]]
repository = 'Shougo/vimshell.git'
mappings = '<Plug>'
# }}}

# Text objects {{{
# textobj-user
[[plugins]]
repository = 'kana/vim-textobj-user'
# vim-textobj-syntax
[[plugins]]
repository = 'kana/vim-textobj-syntax.git'
depends = 'vim-textobj-user'
# vim-textobj-indent
[[plugins]]
repository = 'kana/vim-textobj-indent.git'
depends = 'vim-textobj-user'
# vim-textobj-fold
[[plugins]]
repository = 'kana/vim-textobj-fold.git'
depends = 'vim-textobj-user'
# vim-textobj-lastpat
[[plugins]]
repository = 'kana/vim-textobj-lastpat.git'
depends = 'vim-textobj-user'
[[plugins]]
repository = 'smartword'
mappings = '<Plug>'

# Unit.vim {{{
[[plugins]]
repository = 'Shougo/unite-help'

[[plugins]]
repository = 'tsukkee/unite-tag'

[[plugins]]
repository = 'shougo/unite-outline'

[[plugins]]
repository = 'thinca/vim-unite-history'

[[plugins]]
repository = 'ujihisa/unite-colorscheme'

# }}}

# バブルアップしてファイルを検索
[[plugins]]
repository = 'AtsushiM/search-parent.vim'

# pyenvからpythonを使用
[[plugins]]
repository = 'lambdalisue/vim-pyenv'
#depends = ['', ''] python依存プラグイン
filetypes = ['python', 'python3']


[[plugins]]
repository = 'junegunn/vim-easy-align'
