# ------------------
# #Plugin Lazy sets
# -------------------


[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
# depends = 'unite.vim'
on_map = '<Plug>'
on_path = '.*'


[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'

# Edit{{{

# Completion {{{
# neocomplete.vim
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1
disabled = '!has("lua")'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_i = 1
on_ft = 'snippet'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# }}}


# Languages {{{

# html

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = ['html']

# ブラウザの自動リロード(Mac only!)
[[plugins]]
repo = 'tell-k/vim-browsereload-mac'
on_ft = ['html']

# CSS
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'csscomb/vim-csscomb'
on_ft = ['css', 'scss']

[[plugins]]
repo = 'jasonlong/vim-textobj-css'
on_ft = ['css', 'scss']
depends = 'kana/vim-textobj-user'

[[plugins]]
repo = 'Ioannis-Kapoulas/vim-autoprefixer'
on_ft = ['css', 'scss']
build = 'npm install --global postcss-cli autoprefixer'

# sass
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']


[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'jade', 'css', 'scss']

# XML,HTMLの編集強化
[[plugins]]
repo = 'xmledit'
on_ft = ['html', 'xml']

# haml
[[plugins]]
repo = 'haml.zip'
on_ft = 'haml'

# jade
[[plugins]]
repo = 'digitaltoad/vim-jade'
on_ft = 'jade'

# slim
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

# javascript
[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javaScript', 'jsx']

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javaScript', 'jsx']


# [[plugins]]
# repo = 'carlitux/deoplete-ternjs'
# on_ft = 'javaScript'
# depends = 'deoplete'

# jsx
# [[plugins]]
# repo = 'moll/vim-node'
# on_ft = ['JavaScript', 'jsx']

# jQuery
[[plugins]]
repo = 'jQuery'
on_ft = ['javaScript', 'jsx']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'


# coffee script
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# C
[[plugins]]
repo = 'Rip-Rip/clang_complete'
on_ft = ['c', 'cpp']

# toml(設定ファイル書いたり)
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# yaml
[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yaml'

[[plugins]]
repo = 'sophacles/vim-processing'
on_ft = 'processing'

# }}}

# Markdown {{{
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown', 'md', 'rst']
depends = 'tyru/open-browser.vim'

#URLからブラウザを開く
[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>'


# }}}

# Development {{{
[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'
# }}}

# Searching/Moving{{{
# The Silver seacher
[[plugins]]
repo = 'rking/ag.vim'
on_map = '<Plug>'

# Lint or Checker Tools

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'KazuakiM/vim-qfstatusline'

[[plugins]]
repo = 'KazuakiM/vim-qfsigns'

# [[plugins]]
# repo = 'scrooloose/syntastic'
# on_ft = ['all']

[[plugins]]
repo = 'benekastah/neomake'


# }}}

# Utility {{{

# 編集履歴をツリー表示
[[plugins]]
repo = 'sjl/gundo.vim'
on_map = '<Plug>'

# vimshell
[[plugins]]
repo = 'Shougo/vimshell.git'
on_map = '<Plug>'
# }}}

# Text objects {{{
# textobj-user
[[plugins]]
repo = 'kana/vim-textobj-user'
# vim-textobj-syntax
[[plugins]]
repo = 'kana/vim-textobj-syntax'
depends = 'vim-textobj-user'
# vim-textobj-indent
[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'
# vim-textobj-fold
[[plugins]]
repo = 'kana/vim-textobj-fold'
depends = 'vim-textobj-user'
# vim-textobj-lastpat
[[plugins]]
repo = 'kana/vim-textobj-lastpat'
depends = 'vim-textobj-user'
[[plugins]]
repo = 'smartword'
on_map = '<Plug>'

# Unit.vim {{{
[[plugins]]
repo = 'Shougo/unite-help'
on_source = 'unite.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = 'unite.vim'

[[plugins]]
repo = 'shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = 'unite.vim'

# }}}

# バブルアップしてファイルを検索
[[plugins]]
repo = 'AtsushiM/search-parent.vim'

# pyenvからpythonを使用
[[plugins]]
repo = 'lambdalisue/vim-pyenv'
#depends = ['', ''] python依存プラグイン
on_ft = ['python', 'python3']


[[plugins]]
repo = 'junegunn/vim-easy-align'
