# ------------------
# #Plugin Lazy sets
# -------------------

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
on_map = '<Plug>'
on_if = "isdirectory(bufname('%'))"
hook_source = 'source ~/dotfiles/vim/plugin/vimfiler.vim'
hook_add = '''
  noremap <silent> [vimfiler]t :<C-u>VimFilerBufferDir -winwidth=35 -split -no-quit -simple -toggle<CR>

  nnoremap <silent> [vimfiler]e :<C-u>VimFilerBufferDir -quit<CR>

  augroup vimfiller_setting
    autocmd!
    autocmd FileType vimfiler call s:vimfiler_my_settings()
  augroup END
  function! s:vimfiler_my_settings()
    nmap <buffer> q <Plug>(vimfiler_exit)
    nmap <buffer> Q <Plug>(vimfiler_hide)
    nnoremap <buffer> <C-r> <Plug>(vimfiler_redraw_screen)
    nmap <buffer> <C-q> <Plug>(vimfiler_quick_look)
    nmap <buffer> <C-w> <Plug>(vimfiler_switch_to_history_directory)
    setlocal nonumber
  endfunction
'''

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_source = 'source ~/dotfiles/vim/plugin/unite.vim'
hook_add = '''
  nnoremap [unite]u  :<C-u>Unite -no-split -no-resize -start-insert<Space>
  "全部のせ
  nnoremap <silent> [unite]a :<C-u>UniteWithCurrentDir -no-split -no-resize -start-insert -buffer-name=files buffer file_mru bookmark file<CR>
  " ファイル一覧
  nnoremap <silent> [unite]f :<C-u>Unite -no-split -no-resize -start-insert -buffer-name=files file<CR>
  " バッファー一覧
  nnoremap <silent> [unite]b :<C-u>Unite -no-split -no-resize -start-insert buffer<CR>
  " 常用セット
  nnoremap <silent> [unite]u :<C-u>Unite -no-split -no-resize -start-insert buffer file_mru<CR>
  " 最近使用したファイル一覧
  nnoremap <silent> [unite]m :<C-u>Unite -no-split -no-resize -start-insert file_mru<CR>
  " 現在のバッファのカレントディレクトリからファイル一覧
  nnoremap <silent> [unite]d :<C-u>UniteWithBufferDir -no-split -no-resize -start-insert file<CR>
  " file_recしたディレクトリを表示
  nnoremap <silent> [unite]r :<C-u>Unite -start-insert file_rec/async:!<CR>
  " 検索行を一覧
  nnoremap <silent> [unite]; :<C-u>Unite line<CR>
  " ヤンクヒストリ一覧
  nnoremap <silent> [unite]y :<C-u>Unite history/yank<CR>
  " ヘルプをuniteで表示
  nnoremap <silent> [unite]h :<C-u>Unite -no-split -buffer-name=help help<CR>
  " テキスト、ソースをoutline表示
  nnoremap <silent> [unite]o :<C-u>Unite -no-split -no-resize outline<CR>
  " unite-menudでチートシート
  nnoremap <silent> [unite]l :<C-u>Unite -no-split -no-resize menu<CR>
  " git操作
  nnoremap <silent> [unite]g :<C-u>Unite -start-insert -no-split -no-resize giti<CR>

  function! s:unite_my_settings() abort

    " ESCキーを2回押すと終了する
    nmap <buffer> <ESC> <Plug>(unite_exit)
    nmap <buffer> <ESC><ESC> <Plug>(unite_exit)
    imap <buffer> jj <Plug>(unite_insert_leave)
    nnoremap <silent><buffer> <C-k> :<C-u>call unite#mappings#do_action('preview')<CR>
    imap <buffer> <C-w> <Plug>(unite_delete_backward_path)
    let g:unite_enable_start_insert = 1

    " ウィンドウを分割して開く
    nnoremap <silent> <buffer> <expr> <C-j> unite#do_action('split')
    inoremap <silent> <buffer> <expr> <C-j> unite#do_action('split')

    " ウィンドウを縦に分割して開く
    nnoremap <silent> <buffer> <expr> <C-l> unite#do_action('vsplit')
    inoremap <silent> <buffer> <expr> <C-l> unite#do_action('vsplit')
  endfunction

  augroup unite_settings
    autocmd!
    autocmd FileType unite call s:unite_my_settings()
  augroup END

  " grep検索
  nnoremap <silent> <Leader>g :<C-u>Unite grep:. -buffer-name=search-buffer<CR>
  " ディレクトリを指定してgrep
  nnoremap <silent> <Leader>dg :<C-u>Unite grep -buffer-name=search-buffer<CR>
  " カーソル位置の単語をgrep検索
  nnoremap <silent> <Leader>cg :<C-u>Unite grep:. -buffer-name=search-buffer<CR><C-R><C-W>
  " grep検索結果の再呼出
  nnoremap <silent> <Leader>r :<C-u>UniteResume search-buffer<CR>
  " Bookmarkを開く
  nnoremap <silent> <Leader><Leader>b :<C-u>Unite bookmark<CR>
  " Bookmark追加
  nnoremap <silent> <Leader><Leader>B :<C-u>UniteBookmarkAdd<CR>
'''

# Edit{{{

# Completion {{{
# neocomplete.vim

[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_event = 'InsertEnter'
disabled = '!has("lua")'
hook_source = '''
  let g:loaded_deoplete = 1
  let g:neocomplete#enable_at_startup = 1
  source ~/dotfiles/vim/plugin/neocomplete.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'vim-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_add = '''
  source ~/dotfiles/vim/plugin/neosnippet.vim
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

# }}}


# Languages {{{

# html

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = ['html']

# ブラウザの自動リロード(Mac only!)
[[plugins]]
repo = 'tell-k/vim-browsereload-mac'
on_ft = ['html']

# CSS
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'jasonlong/vim-textobj-css'
on_ft = ['css', 'scss']
depends = 'vim-textobj-user'

[[plugins]]
repo = 'Ioannis-Kapoulas/vim-autoprefixer'
on_ft = ['css', 'scss']
build = 'npm install --global postcss-cli autoprefixer'

# sass
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'jade', 'pug', 'css', 'scss']
hook_add = 'source ~/dotfiles/vim/plugin/emmet.vim'

# XML,HTMLの編集強化
[[plugins]]
repo = 'vim-scripts/xmledit'
on_ft = ['html', 'xml']

# haml
[[plugins]]
repo = 'vim-scripts/haml.zip'
on_ft = 'haml'

# jade
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['jade', 'pug']

# slim
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

# javascript
[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javaScript', 'jsx']

[[plugins]]
repo = 'moll/vim-node'
on_ft = ['javaScript', 'jsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['jsx']
depends = 'vim-javascript'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

# jQuery
[[plugins]]
repo = 'vim-scripts/jQuery'
on_ft = ['javaScript', 'jsx']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

# coffee script
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

# Rails
[[plugins]]
repo = 'tpope/vim-rails'
on_map = '<Plug>'

# C
[[plugins]]
repo = 'Rip-Rip/clang_complete'
on_ft = ['c', 'cpp']

# toml(設定ファイル書いたり)
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# yaml
[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = 'yaml'

[[plugins]]
repo = 'sophacles/vim-processing'
on_ft = 'processing'
hook_source = '''
  let g:processing_fold = 1
'''

# }}}

# Markdown {{{
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'md']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown', 'md', 'rst']

# }}}

# Development {{{

[[plugins]]
repo = 'thinca/vim-qfreplace'
on_ft = ['unite', 'quickfix']
hook_source = '''
  autocmd MyAutoCmd FileType qf nnoremap <buffer> r :<C-u>Qfreplace<CR>
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = [['n', '<Plug>']]
hook_add = 'nmap <silent> <Leader>r <Plug>(quickrun)'
# }}}

# Searching/Moving{{{
# The Silver seacher
[[plugins]]
repo = 'rking/ag.vim'
on_map = '<Plug>'

# Lint or Checker Tools

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'KazuakiM/vim-qfstatusline'

[[plugins]]
repo = 'KazuakiM/vim-qfsigns'

[[plugins]]
repo = 'benekastah/neomake'
hook_source = '''
  source ~/dotfiles/vim/plugin/neomake.vim
'''
hook_add = 'autocmd! BufWritePost * Neomake'

# }}}

# Utility {{{

# 編集履歴をツリー表示
[[plugins]]
repo = 'mbbill/undotree'
on_map = '<Plug>'
hook_add = '''
  set undodir=~/.undodir/
  set undofile
'''
# vimshell
[[plugins]]
repo = 'Shougo/vimshell.git'
on_map = '<Plug>'
# }}}

# Text objects {{{
# vim-textobj-syntax
[[plugins]]
repo = 'kana/vim-textobj-syntax'
depends = 'vim-textobj-user'
# vim-textobj-indent
[[plugins]]
repo = 'kana/vim-textobj-indent'
depends = 'vim-textobj-user'
# vim-textobj-fold
[[plugins]]
repo = 'kana/vim-textobj-fold'
depends = 'vim-textobj-user'
# vim-textobj-lastpat
[[plugins]]
repo = 'kana/vim-textobj-lastpat'
depends = 'vim-textobj-user'
[[plugins]]
repo = 'vim-scripts/smartword'
on_map = '<Plug>'

# Unit.vim {{{
[[plugins]]
repo = 'Shougo/unite-help'
on_source = 'unite.vim'

[[plugins]]
repo = 'tsukkee/unite-tag'
on_source = 'unite.vim'

[[plugins]]
repo = 'shougo/unite-outline'
on_source = 'unite.vim'

[[plugins]]
repo = 'thinca/vim-unite-history'
on_source = 'unite.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'
on_source = 'unite.vim'

[[plugins]]
repo = 'kmnk/vim-unite-giti'
depends = 'unite.vim'
on_source = 'unite.vim'

# }}}

# バブルアップしてファイルを検索
[[plugins]]
repo = 'AtsushiM/search-parent.vim'

# pyenvからpythonを使用
[[plugins]]
repo = 'lambdalisue/vim-pyenv'
#depends = ['', ''] python依存プラグイン
on_ft = ['python', 'python3']

[[plugins]]
repo = 'junegunn/vim-easy-align'
