# ------------------
# #Plugin sets
# -------------------

# Core {{{

# dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# vimproc
[[plugins]]
repo = 'Shougo/vimproc.vim'
  [plugins.build]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

# }}}

# Edit{{{
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Align 整形
[[plugins]]
repo = 'Align'
# surround.vim
[[plugins]]
repo = 'tpope/vim-surround'
# true/false切り替え
[[plugins]]
repo = 'taku-o/vim-toggle'
# コメントアウト
[[plugins]]
repo = 'tomtom/tcomment_vim'
# テキスト整形
[[plugins]]
repo = 'godlygeek/tabular'
# }}}


# Searching/Moving{{{
# smooth_scroll.vim スクロール
[[plugins]]
repo = 'yuroyoro/smooth_scroll.vim'
# 単語移動
# 「%」対応括弧へのカーソル移動を拡張
[[plugins]]
repo = 'matchit.zip'
# }}}


# color scheme
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'othree/yajs'

# ステータスラインの色変更
[[plugins]]
repo = 'itchyny/lightline.vim'

# vimfiler.vim
# 行末の半角スペースを可視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


# Utility {{{

#PATHの設定を自動化
[[plugins]]
repo = 'tpope/vim-bundler'
# git plugin
[[plugins]]
repo = 'tpope/vim-fugitive'
# Helpを日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
# 検索・置換機能強化
[[plugins]]
repo = 'tpope/vim-abolish'
# インデント表示
[[plugins]]
repo = 'Yggdroot/indentLine'
# マークを可視化
[[plugins]]
repo = 'jacquesbh/vim-showmarks'
# }}}

# lint {{{
# [[plugins]]
# repo = 'syngan/vim-vimlint'
# depends = 'vim-vimlparser'


# }}}

