[[plugins]]
# repo = 'Shougo/deoplete.nvim'
# depends = 'context_filetype.vim'
# if = "has('nvim')"
# on_i = 1
# hook_source = '''
#   let g:loaded_neocomplete = 1
#   let g:deoplete#enable_at_startup = 1
#   source ~/dotfiles/vim/plugin/deoplete.vim
# '''
